# Generated by Django 2.1.5 on 2020-09-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
