# Generated by Django 2.1.5 on 2020-09-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200920_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
