# Generated by Django 2.1.5 on 2020-09-21 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200920_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('convo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.Conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to='myapp.Message')),
            ],
        ),
    ]
