# Generated by Django 2.1.5 on 2020-09-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_message_thought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thought',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thought',
            name='title',
            field=models.TextField(),
        ),
    ]
