# Generated by Django 2.1.5 on 2020-09-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200921_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
